name: Market
version: '${project.version}'
main: com.derfacn.market.Market
api-version: '1.21'
commands:
  sell:
    description: Продати предмет
    usage: /sell <ціна>
  market:
    description: Відкрити маркет
    usage: /market <playerName>
  balance:
    description: Управління балансом
    usage: /balance <add|take>
  sales:
    description: Передивитись виставлені предмети
    usage: /sales
  send:
    description: Надіслати ізумруди
    usage: /send <playerName> <amount>