name: Market
version: '${project.version}'
main: com.derfacn.market.Market
api-version: '1.21'
commands:
  sell:
    description: Продати предмет
    usage: /sell <price>
  market:
    description: Відкрити маркет
    usage: /market <playerName|all> <itemName>
  balance:
    description: Управління балансом
    usage: /balance <add|take> <number>
  sales:
    description: Передивитись виставлені предмети
    usage: /sales
  send:
    description: Надіслати ізумруди
    usage: /send <playerName> <amount>
  order:
    description: Зробити замовлення
    usage: /order <item> <count> <price> <days>
  orders:
    description: Переглянути активні замовлення
    usage: /orders
  myorders:
    description: Зняти свої замовлення
    usage: /myorders
  depot:
    description: Склад
    usage: /depot